//! 常駐方法只包含會影響當前操作的規則；完整教學由 read_skill_guide 按頁查回。
pub(super) fn guide(id: &str) -> &'static str {
    match id {
        "python-edit" => "Python修改：create_working_copy後先plan_code_change保存user/preserve/added需求。find_text定位、read_code_section讀小段、edit_code_section用section_hash提交；每段立即保存同一草稿，續接沿用copy_id，不重讀全文。check_python只檢查語法。完成後review_code_change(checks=[])看真實差異與需求，讀相關函式及呼叫處；test_python用unittest.TestCase和load_target()測真正副本，涵蓋預設/正常/邊界/錯誤與輸出，mock要列出。讀read_skill_guide取得測試範例。最後review_code_change逐項提交tested/reviewed/unverified/incomplete與行號證據，才能save_copy；缺依賴或外部環境明示未驗證，不無限重試。測試失敗只修相關段，任何修改使舊驗證失效。交付不可只憑笔記或語法宣稱功能完成。",
        "chart-edit" => "圖表編輯：inspect_chart(null,null)列本輪及同對話歷史圖；指定message_index/chart_index查目前樣式，不重讀來源。edit_chart傳完整style，只改需要欄位，保留其他設定。歷史圖會另建本輪版本，原圖保留；後續用回傳chart_index、message_index=null。layout位置為圖框左上角0–1比例；annotations支援文字/字型/粗斜底線/字色底色。詳細限制見read_skill_guide(chart-edit)。PNG請重新export_chart_png。",
        "python-analysis" => "Python：run_python(purpose,code,inputs)。pd/np/openpyxl/io 已提供；tables[name] 為 DataFrame，texts[name] 為文字，metadata[name] 為來源資訊。inputs 必填 name/path/kind；kind=dataset/csv/text/xlsx。每次是新程序，120秒/1GiB；不能自行開檔、連網或啟動程序。設定 result 為精簡 JSON 結論；emit_table(name,df) 保存 CSV，emit_excel(name,{sheet:df}) 保存 XLSX，成果自動交付。公司原始 Excel 先切換 excel-read，用 COM 匯出追蹤 CSV 再切回。LOG/OUT/ERR 預設 Big5，BOM優先；歧義須核對，metadata.encoding 可查。資料未送模型不代表未計算；保留輸入/成功/排除/失敗/重複/未配對筆數。大型LOG、跨段狀態或特殊輸出先 read_skill_guide(python-analysis)。",
        "excel-read" => "Excel：先 inspect_excel 核對真實欄名與樣本，再 plan_excel_analysis 規劃 x/y/time；用原始欄字母，不重新編號。export_planned_excel 沿用計畫匯出本機CSV。時間序號不能當量測值；欄位意義有多種合理解釋才詢問。一般閱讀 read_excel_range；需要統計切 python-analysis，需要圖表切 dataset-charts。",
        "dataset-charts" => "資料集：確認來源欄位/格式/範圍後 export_excel_dataset 或 export_log_dataset，完整數列留在CSV。inspect_dataset 只看結構與預覽，chart_dataset 直接畫圖，不手抄數列。Excel需要時間篩選先切 excel-read 規劃匯出；複雜LOG先切 python-analysis。缺值保留、異常值按圖表預設且可後改；統計不擅自填零。 set_chart_reference_lines 用現有圖號設定實體X/Y參考線，最多10條；空陣列清除。參數切換取新參數第一筆的座標；類別軸用0起算位置，數值軸用原單位。先完成座標轉換再標線，PNG需重新匯出。需要改標題、顏色、排版或文字，切換chart-edit技能。",
        "charts" => "圖表：優先用現有CSV的 chart_dataset；Excel用 chart_excel_range，來源欄位/版本由程式核對。transform_chart 支援平移/重新編號/全系列無值位置移除，原點陣保留。export_chart_png 取得實際PNG路徑。缺值不代表0；Y空白與異常預設保留缺值，偏好卡片不阻塞；set_chart_policy及編輯器可切換gap/skip/zero。改政策後需要PNG就重新匯出。無效X若deferred先處理其他工作，不能宣稱圖已完成。 set_chart_reference_lines 用現有圖號設定實體X/Y參考線，最多10條；空陣列清除。參數切換取新參數第一筆的座標；類別軸用0起算位置，數值軸用原單位。先完成座標轉換再標線，PNG需重新匯出。需要改標題、顏色、排版或文字，切換chart-edit技能。",
        "log-analysis" => "LOG：先核對樣本、編碼與行格式；read_log 用 revision/next_line 續讀。約略時間先前後5分鐘找事件錨點，無候選才擴到15/30分鐘；有next_cursor就續頁。保留日期來源與未掃描範圍，不能把部分查無結果當不存在。跨行配對/統計切 python-analysis。",
        "outlook-research" | "outlook-coverage" => "Outlook：讀信後下一操作附mail_note保存摘要與草稿；優先read_mail_notes查回；用set_work_stage切換整理、寫入、作圖並選note_ids。由桌面取得勾選範圍同意。識別欄位不足或掃描失敗時，郵件數量未知，不是0封或未授權；勿反覆換日期重試。先 outlook_folders，再 outlook_headers(folder_id,日期,cursor=null)，後續原樣沿用next_cursor。mail_id使用完整回傳代號，遺失或僅記得縮寫時用outlook_index(query,offset)查回本機郵件索引；不猜縮寫、不重建相同查詢。先outlook_compare比較討論串，再outlook_read重要內文；按next_offset續讀。標題/本機比較不算已讀內文。最多AI讀50封，本機比對1000封；不讀附件、不寄信。優先最新信，缺口才補讀。",
        "office-edit" => "Office：create_working_copy 建立或複製；read_file 核對結構及 revision，再 office_batch/office_action 修改，最後save_copy。只有真實copy_id可用；結構改變重新核對區塊ID。原檔/公式/巨集/外部連結不改。PNG只能用已匯出的相對路徑插入，保持比例；詳細操作用read_skill_guide(office-edit)。",
        "weekly-update" => "週報：先讀舊表頭/格式及本週範圍，分清新增、主導、延續與未確認。標題不能當成果、舊計畫不能當完成。按階段切outlook-research讀信、excel-read核對欄位、office-edit改副本。保留日期/來源與使用者篩選條件於工作筆記。",
        "research" | "paper-evidence" => "研究：search_files 找線索，list_document_sections定位，read_document_section核對原文。摘要只作索引，重要數字/單位/否定條件/引文讀原文。品質模型可按需summarize_document，但委派不代表主模型讀完。完整結果留本機；要存長期方法時切notes。",
        "notes" | "context-management" => "記憶：筆記是語意摘要，不取代來源、權限與執行證據。compact_context保存目標/決策/已完成/待辦/下一步，superseded標明失效結論。不要抄入原文。需要精確細節用read_work_log查原版本。record_analysis的證據取實際operation_id與JSON Pointer，統計checks取工具數值，不自填passed。",
        "multi-file-excel" => "多檔Excel：先統一欄位意義/單位與來源，缺資料明示，不猜空值。讀取切excel-read，合併統計切python-analysis，既有表格修改切office-edit。保存對應來源與未完成事項。",
        "text-edit" => "文字：find_text定位原文，create_working_copy後edit_text，只修改副本；每次沿用最新revision，最後save_copy。未知編碼/讀取失敗不猜內容。",
        _ => "",
    }
}
